/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/collectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collectors
         * @description Cursor-paginated list of collectors. Default ordering is `created_at DESC, id DESC`. Pass `?q=<text>` for substring match on name (case-insensitive).
         */
        get: operations["list-collectors"];
        put?: never;
        /**
         * Create a collector
         * @description Creates a new collector. Returns 409 when `name` is non-unique.
         */
        post: operations["create-collector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collectors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a collector by id */
        get: operations["get-collector"];
        put?: never;
        post?: never;
        /**
         * Delete a collector
         * @description Deletes the collector. Returns 409 when the collector is still referenced by `specimen_collectors`.
         */
        delete: operations["delete-collector"];
        options?: never;
        head?: never;
        /**
         * Update a collector
         * @description Partial update; omitted fields keep their previous values. Returns 409 when `name` would collide with another collector.
         */
        patch: operations["patch-collector"];
        trace?: never;
    };
    "/api/v1/journal/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a journal entry by id */
        get: operations["get-journal-entry"];
        put?: never;
        post?: never;
        /**
         * Delete a journal entry
         * @description Returns 409 when the entry still has attachments (`journal_entry_files` rows). Attachment deletion lands in C-2.
         */
        delete: operations["delete-journal-entry"];
        options?: never;
        head?: never;
        /**
         * Update a journal entry
         * @description Updates `body_md` (and re-renders `body_html`). `created_at` is immutable; supplying it in the body is rejected with 400.
         */
        patch: operations["patch-journal-entry"];
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI 3.1 specification
         * @description The machine-readable contract for this API, generated from registered handler types.
         */
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a photo
         * @description Removes the photos row, the files row, and all three MinIO objects (original + display + thumbnail). Best-effort MinIO cleanup; DB transaction is the source of truth.
         */
        delete: operations["delete-photo"];
        options?: never;
        head?: never;
        /** Update a photo's taken_at and/or position */
        patch: operations["patch-photo"];
        trace?: never;
    };
    "/api/v1/specimens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List specimens
         * @description Cursor-paginated list of specimens. Default ordering is `created_at DESC, id DESC`. When `?q=` is present, ordering switches to `ts_rank DESC, created_at DESC, id DESC` and a cursor previously issued under default ordering is rejected (clients discard cursors when filters or `q` change). `?collector_id=` filters to specimens whose chain contains the given collector (mi-zv3).
         */
        get: operations["list-specimens"];
        put?: never;
        /**
         * Create a specimen
         * @description Creates a new specimen. Returns 409 when `catalog_number` is non-unique. The `type` field is immutable after creation (see PATCH).
         */
        post: operations["create-specimen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specimens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specimen by id */
        get: operations["get-specimen"];
        put?: never;
        post?: never;
        /**
         * Delete a specimen
         * @description Deletes the specimen. Cascades to specimen_collectors. Returns 409 when the specimen still has photos or journal entries (those cascades are deferred to B-3 and beyond).
         */
        delete: operations["delete-specimen"];
        options?: never;
        head?: never;
        /**
         * Update a specimen
         * @description Partial update; omitted fields keep previous values. `type_data` is merged at the top level. Sending a `type` that differs from the stored value is rejected with 409 (specimen reclassification means delete + recreate per design §2).
         */
        patch: operations["patch-specimen"];
        trace?: never;
    };
    "/api/v1/specimens/{id}/collectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specimen's collector chain
         * @description Returns the ordered collector chain for the specimen. Empty array when the specimen has no collectors. 404 when the specimen does not exist.
         */
        get: operations["get-specimen-collectors"];
        /**
         * Replace a specimen's collector chain
         * @description Atomically replaces every link in the chain with the supplied collector_ids in order (array index = position, 1-indexed). Pass an empty array to clear the chain. Returns 404 when the specimen does not exist; 404 when any collector_id does not exist; 400 when the body contains duplicate ids.
         */
        put: operations["put-specimen-collectors"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specimens/{id}/journal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a specimen's journal entries
         * @description Cursor-paginated list ordered `created_at DESC, id DESC` (CONTRACT.md §10.3). Each entry includes `body_html` alongside `body_md`.
         */
        get: operations["list-specimen-journal-entries"];
        put?: never;
        /**
         * Create a journal entry for a specimen
         * @description Creates an entry whose body is rendered server-side via the CONTRACT.md §17 markdown pipeline. `created_at` is server-set and immutable after creation.
         */
        post: operations["create-journal-entry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/specimens/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a specimen's photos
         * @description Cursor-paginated list ordered by (position, created_at) ascending — the manual ordering the user controls.
         */
        get: operations["list-specimen-photos"];
        put?: never;
        /**
         * Upload a photo for a specimen
         * @description Multipart upload (`file` form field). Server-side EXIF allowlist filter (drops GPS, XMP, MakerNotes per CONTRACT.md §12), display + thumbnail variant generation, transactional MinIO + Postgres write.
         */
        post: operations["upload-photo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API documentation (Redoc)
         * @description Single-page Redoc viewer that loads the OpenAPI spec from /api/v1/openapi.json.
         */
        get: operations["docs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 with body "ok" if the process is alive. Performs no dependency checks.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Verifies database, storage, and schema version. Returns 200 if all checks pass, 503 with per-check detail otherwise.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ApiError.json
             */
            readonly $schema?: string;
            error: components["schemas"]["ApiErrorBody"];
        };
        ApiErrorBody: {
            /**
             * @description Stable, machine-readable error code (CONTRACT.md §10).
             * @example not_found
             */
            code: string;
            /** @description Optional structured detail; shape varies by error code. */
            details?: {
                [key: string]: unknown;
            };
            /**
             * @description Human-readable error message; not used for client branching.
             * @example resource not found
             */
            message: string;
        };
        CollectorListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/CollectorListBody.json
             */
            readonly $schema?: string;
            /** @description Page of collectors in (created_at DESC, id DESC) order. */
            items: components["schemas"]["CollectorView"][] | null;
            /** @description Cursor for the next page; null at end of results. */
            next_cursor: string | null;
        };
        CollectorView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/CollectorView.json
             */
            readonly $schema?: string;
            /** @description UUID of the user who created the row (CONTRACT.md §13). */
            author_id: string;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp (timestamptz).
             */
            created_at: string;
            /** @description UUIDv7 primary key. */
            id: string;
            /** @description Display name; unique across all collectors. */
            name: string;
            /** @description Optional free-form notes; null when unset. */
            notes: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 last-update timestamp (timestamptz).
             */
            updated_at: string;
        };
        CreateCollectorBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/CreateCollectorBody.json
             */
            readonly $schema?: string;
            /** @description Display name; must be unique. */
            name: string;
            /** @description Optional free-form notes. */
            notes?: string;
        };
        CreateJournalBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/CreateJournalBody.json
             */
            readonly $schema?: string;
            /** @description Markdown source for the entry. Server renders to HTML at write and read time. */
            body_md: string;
        };
        CreateSpecimenBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/CreateSpecimenBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Acquisition date.
             */
            acquired_at?: string;
            /** @description Where the specimen was acquired. */
            acquired_from?: string;
            /** @description Optional unique catalog number. */
            catalog_number?: string;
            /** @description Markdown description; defaults to empty. */
            description?: string;
            /** @description Structured dimensions. */
            dimensions?: components["schemas"]["Dimensions"];
            /** @description Structured locality. */
            locality?: components["schemas"]["Locality"];
            /** @description Free-form locality. */
            locality_text?: string;
            /**
             * Format: double
             * @description Mass in grams.
             */
            mass_g?: number;
            /** @description Display name. */
            name: string;
            /**
             * Format: int64
             * @description Acquisition price in cents.
             */
            price_cents?: number;
            /** @description Free-form provenance notes. */
            source_notes?: string;
            /**
             * @description Specimen kind. Immutable after creation.
             * @enum {string}
             */
            type: "mineral" | "rock" | "meteorite";
            /** @description Type-specific fields; shape selected by the type field. */
            type_data?: components["schemas"]["MineralData"] | components["schemas"]["RockData"] | components["schemas"]["MeteoriteData"];
            /**
             * @description Sharing visibility; defaults to private.
             * @enum {string}
             */
            visibility?: "private" | "unlisted" | "public";
        };
        Dimensions: {
            /** Format: double */
            height_mm?: number;
            /** Format: double */
            length_mm?: number;
            /** Format: double */
            width_mm?: number;
        };
        FormFile: {
            ContentType: string;
            Filename: string;
            IsSet: boolean;
            /** Format: int64 */
            Size: number;
        };
        JournalListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/JournalListBody.json
             */
            readonly $schema?: string;
            /** @description Page of journal entries (most-recent first). */
            items: components["schemas"]["JournalView"][] | null;
            /** @description Cursor for the next page; null at end of results. */
            next_cursor: string | null;
        };
        JournalView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/JournalView.json
             */
            readonly $schema?: string;
            /** @description UUID of the user who created the entry (CONTRACT.md §13). */
            author_id: string;
            /** @description Server-rendered, sanitized HTML (CONTRACT.md §17 pipeline). */
            body_html: string;
            /** @description Raw markdown source (editable for typo fixes). */
            body_md: string;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp; immutable after creation.
             */
            created_at: string;
            /** @description UUIDv7 primary key. */
            id: string;
            /** @description Owning specimen. */
            specimen_id: string;
            /**
             * Format: date-time
             * @description RFC 3339 last-update timestamp.
             */
            updated_at: string;
        };
        Locality: {
            country?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lon?: number;
            mindat_id?: string;
            region?: string;
            site?: string;
        };
        MeteoriteData: {
            classification?: string;
            fall_or_find?: string;
            /** Format: date-time */
            fall_or_find_date?: string;
            metbull_ref?: string;
            official_name?: string;
            /** Format: double */
            total_known_weight_g?: number;
        };
        MineralData: {
            chemical_formula?: string;
            color?: string;
            crystal_system?: string;
            fluorescence?: string;
            luster?: string;
            mindat_id?: string;
            mineral_species?: string[] | null;
            /** Format: double */
            mohs_hardness?: number;
            radioactive?: boolean;
        };
        PatchCollectorBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PatchCollectorBody.json
             */
            readonly $schema?: string;
            /** @description New display name; omit to leave unchanged. */
            name?: string;
            /** @description New notes; omit to leave unchanged. Pass JSON null to clear. */
            notes?: string;
        };
        PatchJournalBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PatchJournalBody.json
             */
            readonly $schema?: string;
            /** @description New markdown source. Omit to leave unchanged. */
            body_md?: string;
            /**
             * Format: date-time
             * @description REJECTED. created_at is immutable per design §2; supplying any value (including the existing one) returns 400.
             */
            created_at?: string;
        };
        PatchPhotoBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PatchPhotoBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description New manual ordering position; omit to leave unchanged.
             */
            position?: number;
            /**
             * Format: date-time
             * @description New taken_at; pass null to clear, omit to leave unchanged.
             */
            taken_at?: string;
        };
        PatchSpecimenBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PatchSpecimenBody.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Omit to leave unchanged.
             */
            acquired_at?: string;
            /** @description Omit to leave unchanged. */
            acquired_from?: string;
            /** @description Omit to leave unchanged; pass null to clear. */
            catalog_number?: string;
            /** @description Omit to leave unchanged. */
            description?: string;
            /** @description Omit to leave unchanged. */
            dimensions?: components["schemas"]["Dimensions"];
            /** @description Omit to leave unchanged. */
            locality?: components["schemas"]["Locality"];
            /** @description Omit to leave unchanged. */
            locality_text?: string;
            /**
             * Format: double
             * @description Omit to leave unchanged.
             */
            mass_g?: number;
            /** @description Omit to leave unchanged. */
            name?: string;
            /**
             * Format: int64
             * @description Omit to leave unchanged.
             */
            price_cents?: number;
            /** @description Omit to leave unchanged. */
            source_notes?: string;
            /**
             * @description Sending a value other than the stored type is rejected with 409 (immutable per design §2).
             * @enum {string}
             */
            type?: "mineral" | "rock" | "meteorite";
            /** @description Top-level merge: present keys overwrite, explicit null clears, omitted keys preserved. */
            type_data?: components["schemas"]["MineralData"] | components["schemas"]["RockData"] | components["schemas"]["MeteoriteData"];
            /**
             * @description Omit to leave unchanged.
             * @enum {string}
             */
            visibility?: "private" | "unlisted" | "public";
        };
        PhotoListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PhotoListBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["PhotoView"][] | null;
            next_cursor: string | null;
        };
        PhotoView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PhotoView.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Byte size of the stored original (post EXIF filter).
             */
            byte_size: number;
            /** @description Content-Type stored on the original file. */
            content_type: string;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp.
             */
            created_at: string;
            /** @description UUID of the underlying files row. */
            file_id: string;
            /** @description UUIDv7 primary key. */
            id: string;
            /**
             * Format: int64
             * @description Manual ordering; 1-indexed within the specimen's photos.
             */
            position: number;
            /** @description Hex SHA-256 of the stored original bytes. */
            sha256: string;
            /** @description Owning specimen. */
            specimen_id: string;
            /**
             * Format: date-time
             * @description When the photo was taken; defaulted from EXIF DateTimeOriginal when not provided.
             */
            taken_at: string | null;
        };
        PutSpecimenCollectorsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/PutSpecimenCollectorsBody.json
             */
            readonly $schema?: string;
            /** @description Ordered list of collector UUIDs. Array index becomes the chain position (1-indexed). Pass an empty array to clear the chain. */
            collector_ids: string[] | null;
        };
        ReadyzBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/ReadyzBody.json
             */
            readonly $schema?: string;
            checks: {
                [key: string]: components["schemas"]["ReadyzCheck"];
            };
            ready: boolean;
        };
        ReadyzCheck: {
            error?: string;
            ok: boolean;
            /** Format: int64 */
            version?: number;
        };
        RockData: {
            composition?: string;
            formation_context?: string;
            rock_type?: string;
        };
        SpecimenCollectorLinkView: {
            /** @description The collector at this position in the chain. */
            collector: components["schemas"]["CollectorView"];
            /**
             * Format: int64
             * @description 1-indexed position within the chain.
             */
            position: number;
        };
        SpecimenCollectorsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/SpecimenCollectorsBody.json
             */
            readonly $schema?: string;
            /** @description Collector chain in position-ascending order. Empty when the specimen has no collectors. */
            items: components["schemas"]["SpecimenCollectorLinkView"][] | null;
        };
        SpecimenListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/SpecimenListBody.json
             */
            readonly $schema?: string;
            /** @description Page of specimens. */
            items: components["schemas"]["SpecimenView"][] | null;
            /** @description Cursor for the next page; null at end of results. */
            next_cursor: string | null;
        };
        SpecimenView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example //schemas/SpecimenView.json
             */
            readonly $schema?: string;
            /**
             * Format: date-time
             * @description Acquisition date (RFC 3339, time component ignored).
             */
            acquired_at: string | null;
            /** @description Where the specimen was acquired (free text). */
            acquired_from: string | null;
            /** @description UUID of the user who created the row (CONTRACT.md §13). */
            author_id: string;
            /** @description Optional human catalog number; unique across all specimens when set. */
            catalog_number: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 creation timestamp.
             */
            created_at: string;
            /** @description Markdown description; defaults to empty string. */
            description: string;
            /** @description Optional structured dimensions. */
            dimensions: components["schemas"]["Dimensions"];
            /** @description UUIDv7 primary key. */
            id: string;
            /** @description Optional structured locality. */
            locality: components["schemas"]["Locality"];
            /** @description Free-form locality (primary display). */
            locality_text: string | null;
            /**
             * Format: double
             * @description Mass in grams.
             */
            mass_g: number | null;
            /** @description Display name. */
            name: string;
            /**
             * Format: int64
             * @description Acquisition price in cents.
             */
            price_cents: number | null;
            /** @description Free-form provenance notes. */
            source_notes: string | null;
            /**
             * @description Specimen kind discriminator (immutable after creation).
             * @enum {string}
             */
            type: "mineral" | "rock" | "meteorite";
            /** @description Type-specific fields; shape governed by the parent type field. */
            type_data: components["schemas"]["MineralData"] | components["schemas"]["RockData"] | components["schemas"]["MeteoriteData"];
            /**
             * Format: date-time
             * @description RFC 3339 last-update timestamp.
             */
            updated_at: string;
            /**
             * @description Sharing visibility.
             * @enum {string}
             */
            visibility: "private" | "unlisted" | "public";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-collectors": {
        parameters: {
            query?: {
                /** @description Page size (1-200; defaults to 50, values above 200 silently clamped). */
                limit?: number;
                /** @description Opaque pagination cursor returned by the previous page (CONTRACT.md §10.3). */
                cursor?: string;
                /** @description Free-form name filter (case-insensitive substring match). */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectorListBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "create-collector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCollectorBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectorView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "get-collector": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collector UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectorView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "delete-collector": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collector UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "patch-collector": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Collector UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchCollectorBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectorView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "get-journal-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Journal entry UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "delete-journal-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Journal entry UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "patch-journal-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Journal entry UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchJournalBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "delete-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "patch-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPhotoBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "list-specimens": {
        parameters: {
            query?: {
                /** @description Page size (1-200; defaults to 50, values above 200 silently clamped). */
                limit?: number;
                /** @description Opaque pagination cursor returned by the previous page (CONTRACT.md §10.3). */
                cursor?: string;
                /** @description Filter by specimen type. */
                type?: "mineral" | "rock" | "meteorite";
                /** @description Filter by visibility. */
                visibility?: "private" | "unlisted" | "public";
                /** @description true returns rows with a catalog_number set; false returns rows without. Omit to disable the filter. */
                has_catalog_number?: "true" | "false";
                /** @description Inclusive lower bound on acquired_at (YYYY-MM-DD). */
                acquired_after?: string;
                /** @description Inclusive upper bound on acquired_at (YYYY-MM-DD). */
                acquired_before?: string;
                /** @description Filter by collector: returns specimens that have the given collector anywhere in their chain (mi-zv3 / C-3). */
                collector_id?: string;
                /** @description Full-text search; when present, ordering switches to ts_rank DESC and any cursor previously issued under default ordering becomes invalid. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenListBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "create-specimen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpecimenBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "get-specimen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "delete-specimen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "patch-specimen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchSpecimenBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "get-specimen-collectors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenCollectorsBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "put-specimen-collectors": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PutSpecimenCollectorsBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecimenCollectorsBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "list-specimen-journal-entries": {
        parameters: {
            query?: {
                /** @description Page size (1-200; defaults to 50, values above 200 silently clamped). */
                limit?: number;
                /** @description Opaque pagination cursor returned by the previous page (CONTRACT.md §10.3). */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalListBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "create-journal-entry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Specimen UUID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJournalBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "list-specimen-photos": {
        parameters: {
            query?: {
                /** @description Page size (1-200; defaults to 50). */
                limit?: number;
                /** @description Opaque pagination cursor returned by the previous page. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoListBody"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "upload-photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The image file to upload.
                     */
                    file: string;
                    /** @description Optional ISO 8601 timestamp; defaults to EXIF DateTimeOriginal when present. */
                    taken_at?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhotoView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    docs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyzBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
