<script lang="ts">
  // SVG QR code renderer (mi-c78.3). Wraps the `qrcode` browser
  // entry's `toString({type:'svg'})` so callers can drop a QR into
  // any container by passing the payload string. The rendered SVG
  // scales with the parent via 100% width/height — sizing is the
  // caller's responsibility.
  import { onMount } from 'svelte';
  import QRCode from 'qrcode';

  interface Props {
    value: string;
    // Display label for screen readers (and as a fallback when SVG
    // generation fails). Required for a11y.
    alt: string;
    errorCorrectionLevel?: 'L' | 'M' | 'Q' | 'H';
    // Quiet zone in modules. Default 1 keeps the printable area tight.
    margin?: number;
  }

  const { value, alt, errorCorrectionLevel = 'M', margin = 1 }: Props = $props();

  let svgMarkup = $state<string>('');
  let renderError = $state<string | null>(null);

  async function render(payload: string): Promise<void> {
    try {
      // toString returns SVG markup with width/height; we strip
      // those so the SVG inherits the parent container's box and
      // print sizing stays in our control.
      const raw = await QRCode.toString(payload, {
        type: 'svg',
        errorCorrectionLevel,
        margin,
      });
      svgMarkup = raw
        .replace(/\swidth="[^"]+"/, '')
        .replace(/\sheight="[^"]+"/, '')
        .replace('<svg ', '<svg width="100%" height="100%" preserveAspectRatio="xMidYMid meet" ');
      renderError = null;
    } catch (err) {
      renderError = err instanceof Error ? err.message : String(err);
      svgMarkup = '';
    }
  }

  onMount(() => {
    void render(value);
  });

  $effect(() => {
    void render(value);
  });
</script>

{#if renderError}
  <span class="text-xs text-red-500" role="img" aria-label={alt} data-testid="qr-error">
    QR error: {renderError}
  </span>
{:else if svgMarkup}
  <div
    class="block h-full w-full"
    role="img"
    aria-label={alt}
    data-testid="qr-svg"
    data-qr-value={value}
  >
    <!--
      `svgMarkup` is generated by the `qrcode` library from a
      string we control (the specimen URL or sheet payload), so
      direct {@html} is the contract's prescribed sink.
    -->
    <!-- eslint-disable-next-line svelte/no-at-html-tags -->
    {@html svgMarkup}
  </div>
{:else}
  <span aria-label={alt} class="sr-only">{alt}</span>
{/if}
